'use client'
import { X, Shield } from 'lucide-react'

interface Props { onClose: () => void }

export default function DisclaimerModal({ onClose }: Props) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{ background: 'var(--bg-overlay)', backdropFilter: 'blur(8px)' }}>
      <div className="w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-2xl shadow-2xl" style={{ background: 'var(--bg-card)', border: '1px solid var(--border-default)' }}>
        <div className="sticky top-0 flex items-center justify-between px-6 py-4 border-b" style={{ background: 'var(--bg-card)', borderColor: 'var(--border-default)' }}>
          <div className="flex items-center gap-3">
            <Shield size={20} style={{ color: 'var(--accent-blue)' }} />
            <h2 className="font-bold text-lg" style={{ color: 'var(--text-primary)' }}>Disclaimer & Usage Terms</h2>
          </div>
          <button onClick={onClose} style={{ color: 'var(--text-dimmer)' }} className="hover:opacity-70 transition-opacity"><X size={20} /></button>
        </div>

        <div className="px-6 py-5 space-y-5 text-sm" style={{ color: 'var(--text-secondary)' }}>
          {[
            ['AI-Generated Content', 'All artifacts generated by this tool are produced by an AI model (Claude by Anthropic). Outputs are starting points for professional review, not final deliverables. Always validate AI-generated content against your specific business context, legal requirements, and team standards before use.'],
            ['No Professional Advice', 'This tool does not constitute legal, compliance, security, financial, or professional engineering advice. STRIDE threat models, compliance checklists, and release criteria generated here must be reviewed by qualified professionals before implementation.'],
            ['Data Handling', 'Your workflow inputs (titles, descriptions, context) are sent to the Anthropic API for processing. Do not enter personally identifiable information (PII), trade secrets, customer data, or confidential proprietary details into this tool. Anthropic\'s usage policies apply to all data processed.'],
            ['No Data Storage', 'Workflow state is held in your browser session memory only. No workflow data is stored on our servers. Refreshing the page or closing the browser clears all workflow data permanently.'],
            ['Accuracy Limitations', 'AI models can hallucinate, omit critical considerations, or generate plausible-sounding but incorrect technical recommendations. The confidence score shown is a self-reported estimate from the AI and should not be treated as a reliability guarantee.'],
            ['Intended Use', 'This tool is intended for software engineering teams to accelerate the creation of SDLC artifacts. It is not intended to replace human judgment, team expertise, or established engineering processes. Use it to augment — not substitute — skilled engineering and product management work.'],
            ['Intellectual Property', 'You retain full ownership of the inputs you provide and the artifacts you produce. Review your organisation\'s AI usage policies before using AI-generated content in production work products.'],
          ].map(([title, body]) => (
            <div key={title as string}>
              <h3 className="font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>{title}</h3>
              <p className="leading-relaxed">{body}</p>
            </div>
          ))}
        </div>

        <div className="px-6 py-4 border-t" style={{ borderColor: 'var(--border-default)' }}>
          <button onClick={onClose} className="w-full py-2.5 rounded-xl font-semibold text-sm text-white"
            style={{ background: 'var(--accent-grad)' }}>
            I Understand
          </button>
        </div>
      </div>
    </div>
  )
}
